# Example configuration file

# Tableau Server connection details
tableau_server_info:
  tableau_server: "<tableau-server-url>"
  site: "<site-name>"
  api_version: "<api-version>"
  token_name: "<personal-access-token-name>"
  token_secret: "<personal-access-token-secret>"

# Other configuration settings
indicator: "<database-type-indicator>"
log_file: "<log_file_name>.txt"

objects:
  - "workbooks"
  - "flows"
  - "datasources"

# Database connection details
snowflake_connection_info:
  db_server_name: "<database-server-name>"
  db_username: "<database-username>"
  db_password: "<database-password>"

databricks_connection_info:
  db_server_name: "<database-server-name>"
  db_username: "<database-username>"
  db_password: "<database-password>"

oracle_connection_info:
  db_server_name: "<database-server-name>"
  db_username: "<database-username>"
  db_password: "<database-password>"